name: Cypress Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
      containers:
        description: 'Number of containers to use'
        required: true
        default: '1'
        type: choice
        options:
          - 1
          - 2
          - 3
          - 4
          - 5

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      BROWSER: ${{ github.event.inputs.browser }}
      CONTAINERS: ${{ github.event.inputs.containers }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ env.BROWSER }}
          record: true
          parallel: true
          config-file: cypress.config.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check generated reports before merging
        run: |
          echo "Listing files in cypress/reports"
          ls -l cypress/reports/
          cat cypress/reports/*.json || echo "No JSON reports generated!"
      - name: Generate HTML report
        run: npm run report
      - name: Upload Mochawesome HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html
